// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sytafe.Server.Data;

#nullable disable

namespace Sytafe.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sytafe.Library.Models.ScreenTimeInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("Anytime")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("AvailableFrom")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("AvailableTo")
                        .HasColumnType("interval");

                    b.Property<string>("DayOfWeek")
                        .HasColumnType("text");

                    b.Property<int>("MinuteLimit")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ScreenTimes");
                });

            modelBuilder.Entity("Sytafe.Library.Models.UsedInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DayOfWeek")
                        .HasColumnType("text");

                    b.Property<DateTime>("From")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("To")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Useds");
                });

            modelBuilder.Entity("Sytafe.Library.Models.UserInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Sytafe.Library.Models.ScreenTimeInfo", b =>
                {
                    b.HasOne("Sytafe.Library.Models.UserInfo", "User")
                        .WithMany("ScreenTimes")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sytafe.Library.Models.UsedInfo", b =>
                {
                    b.HasOne("Sytafe.Library.Models.UserInfo", "User")
                        .WithMany("Useds")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sytafe.Library.Models.UserInfo", b =>
                {
                    b.Navigation("ScreenTimes");

                    b.Navigation("Useds");
                });
#pragma warning restore 612, 618
        }
    }
}
